### PR TITLE
Bugfix/treeview problem

### LINKED ISSUE #628: FHI TreeViewSelection: duplicate ID on checkbox (radio) if more than one instance on same page
### Description

If there are multiple instances of `FhiTreeViewCheckboxComponent` on a single page, clicking on a checkbox label may toggle another checkbox (in an instance higher up on the page).

### What was the expected result?

Only checkbox corresponding to the label being clicked should be toggeled.

### Steps to reproduce

1. Go to https://statistikk.fhi.no/lmr/381qjtUHpsL2f410cT6wFA
2. Open the "Filter"-modal
3. Scroll down to "Kjønn"
4. Toggle "Begge kjønn" by clicking on the label

### Additional information

The reason for this bug is that [the code generating ID's for each selection item](https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/blob/fd36f9b056bd2e3ae8b7551be51ba69b7efa347d/projects/fhi-angular-components/src/lib/fhi-tree-view-selection/fhi-tree-view-selection.component.ts#L221) only creates unique ID's for each item within one instance, it doesn't support uniqueness across instances.

PS. Since the bug is in `FhiTreeViewSelectionComponent` radios has the same problem as the checkboxes, i.e. multiple instances of `FhiTreeViewRadioComponent` also fails.

### PR DESCRIPTION
**Pull request by proand**
This closes #628

### CODE REVIEW

File: projects/fhi-angular-components/src/lib/fhi-tree-view-selection/fhi-tree-view-selection.component.ts [hunk 1]
```diff
@@ -218,14 +214,18 @@ export class FhiTreeViewSelectionComponent implements OnInit, OnChanges {
     return itemsState;
   }
 
-  private createIds(items: Item[], id: number) {
+  private createIds(items: Item[]) {
     items.forEach((item) => {
       if (item.id === undefined) {
-        item.id = id++;
+        item.id = this.getRandomID();
```
Comment (dafn) [inline projects/fhi-angular-components/src/lib/fhi-tree-view-selection/fhi-tree-view-selection.component.ts:220]: If it is a problem at an instance level; do you actually need to create a random id for every item?

Is it possible to create a uuid once for each instance and then add an incrementing number for each item instead?

Comment (proand) [reply projects/fhi-angular-components/src/lib/fhi-tree-view-selection/fhi-tree-view-selection.component.ts:220]: I agree, that is a better solution.

File: projects/fhi-angular-components/src/lib/fhi-tree-view-selection/fhi-tree-view-selection.component.ts [hunk 2]
```diff
@@ -36,11 +37,7 @@ export class FhiTreeViewSelectionComponent implements OnInit, OnChanges {
   filterString = '';
   minimumFilterLength: number = 3;
   searchMode: boolean = false;
-  filterID: string;
-
-  constructor() {
-    this.filterID = 'search-filter-' + this.getRandomID();
-  }
+  instanceID = Math.floor(Math.random() * Math.pow(10, 8));
```
[the remark this answers is not in the document]
Comment (proand) [reply projects/fhi-angular-components/src/lib/fhi-tree-view-selection/fhi-tree-view-selection.component.ts:40]: Nice! Very good suggestion 👍

**Review by dafn — APPROVED** [review]
